### ISSUE TITLE
WhatsApp limit messages per second

### ISSUE THREAD

**Issue by NashIlli** [messagebird/firestore-send-msg#37]
Hello! I read on the docs the following limits
![image](https://user-images.githubusercontent.com/6954280/170378652-89c58784-ded7-4ea4-900d-8eff0ff5d4cf.png)

How many writes in the messages collection can I write per second? What is the limit whit this extenension?

Thanks a lot!

**Comment by aodinok** [comment]
Hello @NashIlli,

There is no limit on extension side. So it should be the same as MessageBird API docs mentions. 

We didn't do high load test for this extension though, so this is theory. If you will face issues with high load, pls let us know. We will try to help!

**Comment by NashIlli** [comment]
Thanks a lot @aodinok 
I'll notice you in case of any issues
